"""add_template_id_to_cards

Revision ID: 91957b3c98bb
Revises: b223bacf8515
Create Date: 2025-03-21 11:53:10.915866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91957b3c98bb'
down_revision: Union[str, None] = 'b223bacf8515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('template_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'cards', 'card_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'template_id')
    # ### end Alembic commands ###
