"""add_background_image_to_templates

Revision ID: b223bacf8515
Revises: 0bfca56bb1a6
Create Date: 2025-03-21 11:27:45.457337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b223bacf8515'
down_revision: Union[str, None] = '0bfca56bb1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_templates', sa.Column('background_image_url', sa.String(), nullable=True))
    op.alter_column('card_templates', 'zones',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_templates', 'zones',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('card_templates', 'background_image_url')
    # ### end Alembic commands ###
